spring:
  data:
    mongodb:
      database: dojo
      host: localhost
      port: 27017

server:
  servlet-path: /system

shell:
  ssh:
    enabled: true
  auth:
    simple:
      user:
        name: dojo
        password: dojo