external:
  config: /tmp/netshoes/config.properties

spring:
  devtools:
    remote:
      secret: dojo
  data:
    mongodb:
      database: dojo
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: dojo
    password: dojo

server:
  servlet-path: /system

shell:
  ssh:
    enabled: true
  auth:
    simple:
      user:
        name: dojo
        password: dojo