external:
  config: /tmp/netshoes/config.properties

spring:
  devtools:
    remote:
      secret: dojo
  data:
    mongodb:
      database: dojo
      host: localhost
      port: 27017

  redis:
    host: localhost
    password: segredo
    port: 6379

server:
  servlet-path: /system

shell:
  ssh:
    enabled: true
  auth:
    simple:
      user:
        name: dojo
        password: dojo