external:
  config: /tmp/netshoes/config.properties

spring:
  devtools:
    remote:
      secret: dojo
  data:
    mongodb:
      database: dojo
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: dojo
    password: dojo
  jpa:
    hibernate:
      ddl-auto: create-drop

  redis:
    host: localhost
    password: segredo
    port: 6379

minio:
  host: http://localhost:9000
  access-key: N4BEIOH6PAHSG25I4TFI
  secret-key: YN65o85VPABXYzYHbs4aNPdGotLknXmKokz91+3m

server:
  servlet-path: /system

shell:
  ssh:
    enabled: true
  auth:
    simple:
      user:
        name: dojo
        password: dojo

domains:
  access:
    control:
      allow:
        origin: '*'